version: '3.4'

services:
  webrtc:
    image: webrtc
    build:
      context: trunk/3rdparty/srs-bench/vendor/github.com/pion/webrtc/v3
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
